version: '3.7'

services:
  backend:
    image: ghcr.io/marc1307/duo-ise-portal-backend:main
    container_name: backend
    restart: always
    volumes:
      - ./config.ini:/app/config.ini:ro
    expose: 
      - 8080

  frontend:
    image: ghcr.io/marc1307/duo-ise-portal-frontend:main
    container_name: frontend
    restart: always
    depends_on: 
      - backend
    ports:
      - 8444:80
