version: '3.7'

services:
  backend:
    build: ./backend
    container_name: backend
    restart: always
    volumes:
      - ./config.ini.prod:/app/config.ini:ro
    expose: 
      - 8080

  frontend:
    build: ./frontend
    container_name: frontend
    restart: always
    depends_on: 
      - backend
    ports:
      - 8444:80
